#!/usr/bin/env python3
"""Consumer-owned task-runner bridge generated by Agentic Factory."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMAND = [sys.executable, str(ROOT / "vendor/sdd-harness-guardian/scripts/validate_human_visibility.py"), "--consumer-root", str(ROOT), "--initiative"]
raise SystemExit(subprocess.call(COMMAND + sys.argv[1:]))
